name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  results:
    # This job was inspired by https://github.com/orgs/community/discussions/26822#discussioncomment-5122101
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [docker]
    steps:
      - run: exit 1
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}

  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - alpine-latest
          - alpine-edge
          - alpine-3.15.0
          - alpine-3.10
        include:
          - tag: alpine-latest
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
            extra_packages: hugo-bash-completion
          - tag: alpine-edge
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/riscv64
            extra_packages: hugo-bash-completion
          - tag: alpine-3.15.0
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
            extra_packages: hugo-bash-completion
          - tag: alpine-3.10
            platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platforms }}
          context: ./${{ matrix.tag }}
          push: ${{ github.event_name == 'push' }}
          tags: pizzafactory0contorno/hugo:${{ matrix.tag }}
          build-args: EXTRA_PACKAGES=${{ matrix.extra_packages }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=${{ matrix.tag }}
